# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/clion/CLion-2025.2.2/clion-2025.2.2/bin/cmake/linux/x64/bin/cmake

# The command to remove a file.
RM = /opt/clion/CLion-2025.2.2/clion-2025.2.2/bin/cmake/linux/x64/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/adminpc/ViSION/Reborn-Vision-2024-armor-Inference-main

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/adminpc/ViSION/Reborn-Vision-2024-armor-Inference-main

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/opt/clion/CLion-2025.2.2/clion-2025.2.2/bin/cmake/linux/x64/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/clion/CLion-2025.2.2/clion-2025.2.2/bin/cmake/linux/x64/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/adminpc/ViSION/Reborn-Vision-2024-armor-Inference-main/CMakeFiles /home/adminpc/ViSION/Reborn-Vision-2024-armor-Inference-main//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/adminpc/ViSION/Reborn-Vision-2024-armor-Inference-main/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named INFERENCE

# Build rule for target.
INFERENCE: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 INFERENCE
.PHONY : INFERENCE

# fast build rule for target.
INFERENCE/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/INFERENCE.dir/build.make CMakeFiles/INFERENCE.dir/build
.PHONY : INFERENCE/fast

src/inference.o: src/inference.cpp.o
.PHONY : src/inference.o

# target to build an object file
src/inference.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/INFERENCE.dir/build.make CMakeFiles/INFERENCE.dir/src/inference.cpp.o
.PHONY : src/inference.cpp.o

src/inference.i: src/inference.cpp.i
.PHONY : src/inference.i

# target to preprocess a source file
src/inference.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/INFERENCE.dir/build.make CMakeFiles/INFERENCE.dir/src/inference.cpp.i
.PHONY : src/inference.cpp.i

src/inference.s: src/inference.cpp.s
.PHONY : src/inference.s

# target to generate assembly for a file
src/inference.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/INFERENCE.dir/build.make CMakeFiles/INFERENCE.dir/src/inference.cpp.s
.PHONY : src/inference.cpp.s

src/number_classifier.o: src/number_classifier.cpp.o
.PHONY : src/number_classifier.o

# target to build an object file
src/number_classifier.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/INFERENCE.dir/build.make CMakeFiles/INFERENCE.dir/src/number_classifier.cpp.o
.PHONY : src/number_classifier.cpp.o

src/number_classifier.i: src/number_classifier.cpp.i
.PHONY : src/number_classifier.i

# target to preprocess a source file
src/number_classifier.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/INFERENCE.dir/build.make CMakeFiles/INFERENCE.dir/src/number_classifier.cpp.i
.PHONY : src/number_classifier.cpp.i

src/number_classifier.s: src/number_classifier.cpp.s
.PHONY : src/number_classifier.s

# target to generate assembly for a file
src/number_classifier.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/INFERENCE.dir/build.make CMakeFiles/INFERENCE.dir/src/number_classifier.cpp.s
.PHONY : src/number_classifier.cpp.s

src/tradition.o: src/tradition.cpp.o
.PHONY : src/tradition.o

# target to build an object file
src/tradition.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/INFERENCE.dir/build.make CMakeFiles/INFERENCE.dir/src/tradition.cpp.o
.PHONY : src/tradition.cpp.o

src/tradition.i: src/tradition.cpp.i
.PHONY : src/tradition.i

# target to preprocess a source file
src/tradition.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/INFERENCE.dir/build.make CMakeFiles/INFERENCE.dir/src/tradition.cpp.i
.PHONY : src/tradition.cpp.i

src/tradition.s: src/tradition.cpp.s
.PHONY : src/tradition.s

# target to generate assembly for a file
src/tradition.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/INFERENCE.dir/build.make CMakeFiles/INFERENCE.dir/src/tradition.cpp.s
.PHONY : src/tradition.cpp.s

src/video_detect_test.o: src/video_detect_test.cpp.o
.PHONY : src/video_detect_test.o

# target to build an object file
src/video_detect_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/INFERENCE.dir/build.make CMakeFiles/INFERENCE.dir/src/video_detect_test.cpp.o
.PHONY : src/video_detect_test.cpp.o

src/video_detect_test.i: src/video_detect_test.cpp.i
.PHONY : src/video_detect_test.i

# target to preprocess a source file
src/video_detect_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/INFERENCE.dir/build.make CMakeFiles/INFERENCE.dir/src/video_detect_test.cpp.i
.PHONY : src/video_detect_test.cpp.i

src/video_detect_test.s: src/video_detect_test.cpp.s
.PHONY : src/video_detect_test.s

# target to generate assembly for a file
src/video_detect_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/INFERENCE.dir/build.make CMakeFiles/INFERENCE.dir/src/video_detect_test.cpp.s
.PHONY : src/video_detect_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... INFERENCE"
	@echo "... src/inference.o"
	@echo "... src/inference.i"
	@echo "... src/inference.s"
	@echo "... src/number_classifier.o"
	@echo "... src/number_classifier.i"
	@echo "... src/number_classifier.s"
	@echo "... src/tradition.o"
	@echo "... src/tradition.i"
	@echo "... src/tradition.s"
	@echo "... src/video_detect_test.o"
	@echo "... src/video_detect_test.i"
	@echo "... src/video_detect_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

